[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "innowise_laboratory"
version = "0.1.0"
dependencies = [
    "colorama==0.4.6"
]

[tool.setuptools]
packages = ["lecture_1"]
